// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzgaoyceskwebjyqqypz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6Z2FveWNlc2t3ZWJqeXFxeXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTYzMzYsImV4cCI6MjA2OTQ3MjMzNn0.XutPTpFSkj_gjbz9Jw4ez8hx4OIwV8wgoVoHXcdAjc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});